# Generated by Django 4.2.20 on 2026-03-20 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='trophy', help_text='Nombre del icono SVG en assets/icons/', max_length=50)),
                ('category', models.CharField(choices=[('RANKING', 'Ranking'), ('RACHA', 'Racha'), ('PRECISION', 'Precisión'), ('ESPECIAL', 'Especial')], default='ESPECIAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos variables del logro: ciudad, mes, año, etc.')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='ranking.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de usuario',
                'verbose_name_plural': 'Logros de usuarios',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(help_text='1=Enero, 12=Diciembre', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('correct_guesses', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntuación mensual',
                'verbose_name_plural': 'Puntuaciones mensuales',
                'ordering': ['-year', '-month', '-total_score'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
