# Generated by Django 4.2.20 on 2026-06-09 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyscore',
            name='month',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='1=Enero, 12=Diciembre', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='monthlyscore',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
