# Generated by Django 4.2.20 on 2026-03-20 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Identificador de sesión anónima', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('clues_revealed', models.PositiveSmallIntegerField(default=1, help_text='Número de pistas reveladas hasta ahora (empieza en 1)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('final_score', models.PositiveSmallIntegerField(default=0)),
                ('movie_guessed', models.BooleanField(default=False)),
                ('guessed_at_clue', models.PositiveSmallIntegerField(blank=True, help_text='En qué pista acertó el usuario (1-4). Null si no acertó', null=True)),
                ('daily_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movies.dailytest')),
                ('user', models.ForeignKey(blank=True, help_text='Null si el jugador no está logueado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de juego',
                'verbose_name_plural': 'Sesiones de juego',
            },
        ),
        migrations.CreateModel(
            name='GuessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_number', models.PositiveSmallIntegerField(help_text='1-4: intento en la pista X. 5: intento final (sin puntos)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attempt_text', models.CharField(help_text='Lo que escribió el usuario', max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.gamesession')),
            ],
            options={
                'verbose_name': 'Intento de respuesta',
                'verbose_name_plural': 'Intentos de respuesta',
                'ordering': ['game_session', 'attempted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'daily_test'), name='unique_user_daily_test'),
        ),
    ]
