# Generated by Django 4.2.20 on 2026-03-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamesession',
            name='unique_user_daily_test',
        ),
    ]
