# Generated by Django 4.2.20 on 2026-03-20 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('omdb_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('lead_actor', models.CharField(blank=True, max_length=200)),
                ('screenwriter', models.CharField(blank=True, max_length=200)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=150)),
                ('production_country', models.CharField(blank=True, max_length=100)),
                ('letterboxd_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('oscar_nominations', models.PositiveSmallIntegerField(default=0)),
                ('oscar_wins', models.PositiveSmallIntegerField(default=0)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('iconic_quote', models.TextField(blank=True)),
                ('spotify_track_id', models.CharField(blank=True, max_length=100)),
                ('is_candidate', models.BooleanField(default=True, help_text='Importada de la API, pendiente de revisión por el admin')),
                ('is_selected', models.BooleanField(default=False, help_text='Elegida por el admin para asignarse a un día concreto')),
                ('is_used', models.BooleanField(default=False, help_text='Ya fue usada como test diario. No repetir en 1 año')),
                ('used_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DailyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_tests', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Test diario',
                'verbose_name_plural': 'Tests diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_type', models.CharField(choices=[('IMAGE', 'Fotograma de la película'), ('AUDIO', 'Fragmento de banda sonora'), ('DIRECTOR', 'Director'), ('ACTOR', 'Actor/Actriz protagonista'), ('YEAR', 'Año de estreno'), ('LETTERBOXD', 'Puntuación en Letterboxd'), ('OSCARS', 'Número de Oscars'), ('ICONIC_QUOTE', 'Frase icónica'), ('GENRE', 'Género'), ('DURATION', 'Duración'), ('COUNTRY', 'País de producción'), ('SCREENWRITER', 'Guionista')], help_text='Tipo de pista. No puede repetirse en el mismo test', max_length=20)),
                ('order', models.PositiveSmallIntegerField(help_text='Posición de revelación: 1 (primera) a 4 (última)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('content_text', models.TextField(blank=True, help_text='Para tipos: DIRECTOR, ACTOR, YEAR, LETTERBOXD, OSCARS, ICONIC_QUOTE, GENRE, DURATION, COUNTRY, SCREENWRITER')),
                ('content_image', models.ImageField(blank=True, help_text='Para tipo IMAGE: fotograma de la película', null=True, upload_to='frames/')),
                ('content_audio', models.FileField(blank=True, help_text='Para tipo AUDIO: fragmento MP3 de menos de 30 segundos', null=True, upload_to='audio/')),
                ('daily_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='movies.dailytest')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
                'ordering': ['daily_test', 'order'],
                'unique_together': {('daily_test', 'clue_type'), ('daily_test', 'order')},
            },
        ),
    ]
