# Generated by Django 4.2.20 on 2026-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='franchise_name',
            field=models.CharField(blank=True, help_text='Nombre de la saga. Si se rellena, se acepta como respuesta alternativa.', max_length=255),
        ),
    ]
