# Generated by Django 4.2.20 on 2026-03-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_franchise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedMovie',
            fields=[
            ],
            options={
                'verbose_name': 'Película seleccionada',
                'verbose_name_plural': 'Películas seleccionadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.movie',),
        ),
        migrations.CreateModel(
            name='UsedMovie',
            fields=[
            ],
            options={
                'verbose_name': 'Película usada',
                'verbose_name_plural': 'Películas usadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.movie',),
        ),
    ]
