# Generated by Django 4.2.20 on 2026-04-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_selectedmovie_usedmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBackdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = más relevante')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backdrops', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Fotograma',
                'verbose_name_plural': 'Fotogramas',
                'ordering': ['movie', 'order'],
            },
        ),
    ]
