# Generated by Django 4.2.20 on 2026-04-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviebackdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rt_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puntuación en Rotten Tomatoes (0-100). Se importa automáticamente desde OMDb.', null=True),
        ),
    ]
