# Generated by Django 4.2.20 on 2026-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_rt_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='letterboxd_score',
        ),
        migrations.AlterField(
            model_name='clue',
            name='clue_type',
            field=models.CharField(choices=[('IMAGE', 'Fotograma de la película'), ('AUDIO', 'Fragmento de banda sonora'), ('DIRECTOR', 'Director'), ('ACTOR', 'Actor/Actriz protagonista'), ('YEAR', 'Año de estreno'), ('ROTTEN_TOMATOES', 'Valoración en Rotten Tomatoes'), ('OSCARS', 'Número de Oscars'), ('ICONIC_QUOTE', 'Frase icónica'), ('GENRE', 'Género'), ('DURATION', 'Duración'), ('COUNTRY', 'País de producción'), ('SCREENWRITER', 'Guionista')], help_text='Tipo de pista. No puede repetirse en el mismo test', max_length=20),
        ),
        migrations.AlterField(
            model_name='clue',
            name='content_text',
            field=models.TextField(blank=True, help_text='Para tipos: DIRECTOR, ACTOR, YEAR, ROTTEN_TOMATOES, OSCARS, ICONIC_QUOTE, GENRE, DURATION, COUNTRY, SCREENWRITER'),
        ),
    ]
