# Generated by Django 4.2.20 on 2026-04-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_letterboxd_score_alter_clue_clue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='oscar_categories',
            field=models.JSONField(blank=True, default=list, help_text='Categorías de Oscar ganadas. Se importa automáticamente desde Wikidata.'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clue_type',
            field=models.CharField(choices=[('IMAGE', 'Fotograma de la película'), ('AUDIO', 'Fragmento de banda sonora'), ('DIRECTOR', 'Director'), ('ACTOR', 'Actor/Actriz protagonista'), ('YEAR', 'Año de estreno'), ('ROTTEN_TOMATOES', 'Valoración en Rotten Tomatoes'), ('OSCARS', 'Número de Oscars'), ('OSCAR_CATEGORIES', 'Categorías de Oscar ganadas'), ('ICONIC_QUOTE', 'Frase icónica'), ('GENRE', 'Género'), ('DURATION', 'Duración'), ('COUNTRY', 'País de producción'), ('SCREENWRITER', 'Guionista')], help_text='Tipo de pista. No puede repetirse en el mismo test', max_length=20),
        ),
    ]
