# Generated by Django 4.2.20 on 2026-04-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_oscar_categories_alter_clue_clue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='oscar_categories',
            field=models.JSONField(blank=True, default=dict, help_text='Dict {"won": [...], "nominated": [...]}. Se importa desde Wikidata.'),
        ),
    ]
