# Generated by Django 4.2.20 on 2026-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_audio_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='clue_type',
            field=models.CharField(choices=[('IMAGE', 'Fotograma de la película'), ('DIRECTOR', 'Director'), ('ACTOR', 'Actor/Actriz protagonista'), ('YEAR', 'Año de estreno'), ('ROTTEN_TOMATOES', 'Valoración en Rotten Tomatoes'), ('OSCARS', 'Número de Oscars'), ('OSCAR_CATEGORIES', 'Categorías de Oscar ganadas'), ('ICONIC_QUOTE', 'Frase icónica'), ('GENRE', 'Género'), ('DURATION', 'Duración'), ('COUNTRY', 'País de producción'), ('SCREENWRITER', 'Guionista')], help_text='Tipo de pista. No puede repetirse en el mismo test', max_length=20),
        ),
        migrations.AlterField(
            model_name='clue',
            name='content_text',
            field=models.TextField(blank=True, help_text='Para tipos: DIRECTOR, ACTOR, YEAR, ROTTEN_TOMATOES, OSCARS, OSCAR_CATEGORIES, ICONIC_QUOTE, GENRE, DURATION, COUNTRY, SCREENWRITER'),
        ),
    ]
